name: 更新热榜数据

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-hot-news:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置超时时间为10分钟

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          
      - name: 更新知乎热榜
        run: |
          python _scripts/update_zhihu_hot.py
        continue-on-error: true  # 即使脚本失败也继续执行
          
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add source/_data/zhihu.json
          git diff --staged --quiet || git commit -m "自动更新热榜数据 $(date +'%Y-%m-%d %H:%M:%S')"
          
      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 